# Generated by Django 3.2.16 on 2022-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221121_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_booking',
            field=models.BooleanField(default=False, verbose_name='Бронирует'),
        ),
    ]
