# Generated by Django 3.2.16 on 2022-11-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_parkingplace_parkingplacetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='main.parkingplacestatus'),
        ),
    ]
