# Generated by Django 3.2.16 on 2022-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221201_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(0, 'Открытое'), (1, 'Крытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
    ]
