# Generated by Django 3.2.16 on 2022-12-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_preferences_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplacetype',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(0, 'Открытое'), (1, 'Крытое')], default=0, null=True, verbose_name='Открытое-закрытое'),
        ),
    ]
