# Generated by Django 3.2.16 on 2022-12-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_parkingplace_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplacetype',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(0, 'Открытое'), (1, 'Крытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
        migrations.AlterField(
            model_name='parkingplacetype',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, 'Рядом со входом'), (0, 'Рядом с выездом')], null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(0, 'Открытое'), (1, 'Крытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, 'Рядом со входом'), (0, 'Рядом с выездом')], null=True, verbose_name='Расположение'),
        ),
    ]
