# Generated by Django 3.2.16 on 2022-12-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221201_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplacetype',
            name='location',
            field=models.IntegerField(blank=True, choices=[(0, 'Рядом с выездом'), (1, 'Рядом со входом')], null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='location',
            field=models.IntegerField(blank=True, choices=[(0, 'Рядом с выездом'), (1, 'Рядом со входом')], null=True, verbose_name='Расположение'),
        ),
    ]
