# Generated by Django 3.2.16 on 2022-12-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20221201_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booked_place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='main.parkingplace'),
        ),
    ]
