# Generated by Django 4.1.3 on 2022-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_booked_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplacetype',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(1, 'Крытое'), (0, 'Открытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
        migrations.AlterField(
            model_name='parkingplacetype',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, 'Рядом со входом'), (0, 'Рядом с выездом')], null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(1, 'Крытое'), (0, 'Открытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, 'Рядом со входом'), (0, 'Рядом с выездом')], null=True, verbose_name='Расположение'),
        ),
    ]
