# Generated by Django 4.1.3 on 2022-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_parkingplacetype_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkingplacetype',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(0, 'Открытое'), (1, 'Крытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='is_open',
            field=models.IntegerField(blank=True, choices=[(0, 'Открытое'), (1, 'Крытое')], null=True, verbose_name='Открытое-закрытое'),
        ),
    ]
