# Generated by Django 4.1.3 on 2022-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_question_link_alter_parkingplacetype_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parkingplacetype',
            name='location',
            field=models.IntegerField(blank=True, choices=[(0, 'Рядом с выездом'), (1, 'Рядом со входом')], null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='location',
            field=models.IntegerField(blank=True, choices=[(0, 'Рядом с выездом'), (1, 'Рядом со входом')], null=True, verbose_name='Расположение'),
        ),
    ]
