# Generated by Django 4.1.3 on 2022-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_log_date_alter_parkingplacetype_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
